{% set name = "new_conda_env" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CatChenal/new_conda_env/archive/v{{ version }}.tar.gz
  sha256: 3b10f8e0592923eedad6519c6e1eef08c49e88e65ff235477bec1edd989679ac

build:
  entry_points:
    - new-conda-env = new_conda_env.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda

test:
  imports:
    - new_conda_env
  commands:
    - pip check
    - new-conda-env --help
  requires:
    - pip

about:
  home: https://github.com/CatChenal/new_conda_env
  summary: "A Python package for generating a 'lean' environment yaml file (see README)."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CatChenal
